# Generated by Django 3.0.8 on 2020-07-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('starting_bid', models.IntegerField()),
                ('Categories', models.CharField(choices=[('T', 'Toys'), ('F', 'Fashion'), ('E', 'Electronics'), ('H', 'Home'), ('O', 'Others')], max_length=10)),
            ],
        ),
    ]
