# Generated by Django 3.0.8 on 2020-07-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200728_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(null=True, upload_to='auctions/pictures'),
        ),
    ]
