# Generated by Django 3.0.8 on 2020-07-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200728_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(null=True, upload_to='auctions/static/img'),
        ),
    ]
