# Generated by Django 3.0.8 on 2020-08-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200805_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='auctions.Listings'),
        ),
    ]
