# Generated by Django 3.0.8 on 2020-08-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
