# Generated by Django 3.0.8 on 2020-08-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200810_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, null=True)),
                ('bid', models.IntegerField(null=True)),
                ('item_id', models.IntegerField(null=True)),
            ],
        ),
    ]
