# Generated by Django 3.0.8 on 2020-08-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='close_bid',
            field=models.BooleanField(null=True),
        ),
    ]
