# Generated by Django 3.0.8 on 2020-08-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_bids_close_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='close_bid',
            field=models.BooleanField(null=True),
        ),
    ]
