# Generated by Django 3.0.8 on 2020-08-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_listings_close_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField(null=True)),
                ('winner_username', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bids',
            name='close_bid',
        ),
    ]
