# Generated by Django 3.0.8 on 2020-12-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_summary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='summary',
            table='summary',
        ),
    ]
