# Generated by Django 3.0.8 on 2020-12-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20201219_1745'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='summary',
            table=None,
        ),
    ]
