# Generated by Django 3.0.8 on 2020-12-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20201219_1757'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='summary',
            table='summary',
        ),
    ]
