# Generated by Django 3.0.8 on 2020-12-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20201220_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
