# Generated by Django 3.0.8 on 2020-12-20 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_transactions_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='auctions.Listings'),
        ),
    ]
